#!/usr/bin/env bash
# -----------------------------------------------------------
# Generic assignment reviewer
# Usage: review-hw.sh <hw_number>
# Reads a config file at .github/scripts/hw<N>.conf and runs
# file-existence + grep checks, then emits a Markdown checklist.
# -----------------------------------------------------------
set -euo pipefail

HW="$1"
CONF=".github/scripts/hw${HW}.conf"
ROOT="bim308_hw${HW}"

if [[ ! -f "$CONF" ]]; then
  echo "No config found for HW${HW} at ${CONF}" >&2
  exit 1
fi

PASS=0
FAIL=0
BODY=""

section() {
  BODY+=$'\n'"## $1"$'\n'
}

check_file() {
  local label="$1" path="$2"
  if [[ -f "$path" ]]; then
    BODY+="- [x] ${label}"$'\n'
    PASS=$((PASS + 1))
  else
    BODY+="- [ ] ${label} — **missing:** \`${path}\`"$'\n'
    FAIL=$((FAIL + 1))
  fi
}

check_dir() {
  local label="$1" path="$2"
  if [[ -d "$path" ]]; then
    BODY+="- [x] ${label}"$'\n'
    PASS=$((PASS + 1))
  else
    BODY+="- [ ] ${label} — **missing:** \`${path}\`"$'\n'
    FAIL=$((FAIL + 1))
  fi
}

check_grep() {
  local label="$1" pattern="$2" path="$3"
  if [[ -f "$path" ]] && grep -qE "$pattern" "$path" 2>/dev/null; then
    BODY+="- [x] ${label}"$'\n'
    PASS=$((PASS + 1))
  else
    BODY+="- [ ] ${label} — **not found** in \`${path}\`"$'\n'
    FAIL=$((FAIL + 1))
  fi
}

check_grep_dir() {
  local label="$1" pattern="$2" dir="$3" glob="$4"
  if find "$dir" -name "$glob" -exec grep -lE "$pattern" {} + 2>/dev/null | head -1 | grep -q .; then
    BODY+="- [x] ${label}"$'\n'
    PASS=$((PASS + 1))
  else
    BODY+="- [ ] ${label} — **not found** in \`${dir}/${glob}\`"$'\n'
    FAIL=$((FAIL + 1))
  fi
}

check_count() {
  local label="$1" pattern="$2" path="$3" min="$4"
  if [[ -f "$path" ]]; then
    local count
    count=$(grep -cE "$pattern" "$path" 2>/dev/null || echo 0)
    if [[ "$count" -ge "$min" ]]; then
      BODY+="- [x] ${label} (found ${count})"$'\n'
      PASS=$((PASS + 1))
    else
      BODY+="- [ ] ${label} — found ${count}, need at least ${min}"$'\n'
      FAIL=$((FAIL + 1))
    fi
  else
    BODY+="- [ ] ${label} — **file missing:** \`${path}\`"$'\n'
    FAIL=$((FAIL + 1))
  fi
}

# Source the config (it calls the functions above)
# shellcheck disable=SC1090
source "$CONF"

TOTAL=$((PASS + FAIL))

if [[ "$FAIL" -eq 0 ]]; then
  STATUS="PASSED"
  EMOJI="white_check_mark"
else
  STATUS="NEEDS WORK"
  EMOJI="warning"
fi

HEADER=":${EMOJI}: **Claude Review — BIM308 HW${HW}** | **${PASS}/${TOTAL}** checks passed | Status: **${STATUS}**"
HEADER+=$'\n\n'"_Auto-generated by GitHub Actions on $(date -u +%Y-%m-%d). Push to \`bim308_hw${HW}/\` to re-run._"
HEADER+=$'\n'"---"

echo "${HEADER}${BODY}"
