// <auto-generated />
using BookLibraryEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookLibraryEF.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260321201501_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookLibraryEF.Models.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorID"));

                    b.Property<string>("AuthorInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorID = 1,
                            AuthorInfo = "American novelist, widely regarded as one of the greatest writers of the 20th century.",
                            AuthorName = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            AuthorID = 2,
                            AuthorInfo = "American novelist best known for her Pulitzer Prize-winning novel.",
                            AuthorName = "Harper Lee"
                        },
                        new
                        {
                            AuthorID = 3,
                            AuthorInfo = "English novelist and essayist, known for his sharp criticism of political oppression.",
                            AuthorName = "George Orwell"
                        },
                        new
                        {
                            AuthorID = 4,
                            AuthorInfo = "English novelist known for her commentary on the British landed gentry.",
                            AuthorName = "Jane Austen"
                        },
                        new
                        {
                            AuthorID = 5,
                            AuthorInfo = "American writer known for his widely-read novel about teenage angst.",
                            AuthorName = "J.D. Salinger"
                        },
                        new
                        {
                            AuthorID = 6,
                            AuthorInfo = "Founder of the Republic of Turkey and its first President.",
                            AuthorName = "Mustafa Kemal Ataturk"
                        });
                });

            modelBuilder.Entity("BookLibraryEF.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            AuthorID = 1,
                            ImageUrl = "https://m.media-amazon.com/images/I/71FTb9X6wsL._SY466_.jpg",
                            Price = 12.99,
                            ReleaseYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookID = 2,
                            AuthorID = 2,
                            ImageUrl = "https://m.media-amazon.com/images/I/81gepf1eMqL._SY466_.jpg",
                            Price = 14.99,
                            ReleaseYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookID = 3,
                            AuthorID = 3,
                            ImageUrl = "https://m.media-amazon.com/images/I/71kxa1-0mfL._SY466_.jpg",
                            Price = 13.99,
                            ReleaseYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            BookID = 4,
                            AuthorID = 4,
                            ImageUrl = "https://m.media-amazon.com/images/I/71Q1tPupKjL._SY466_.jpg",
                            Price = 11.99,
                            ReleaseYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            BookID = 5,
                            AuthorID = 5,
                            ImageUrl = "https://m.media-amazon.com/images/I/8125BDk3l9L._SY466_.jpg",
                            Price = 10.99,
                            ReleaseYear = 1951,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            BookID = 6,
                            AuthorID = 6,
                            ImageUrl = "https://m.media-amazon.com/images/I/51KMDtNclHL._SY466_.jpg",
                            Price = 19.390000000000001,
                            ReleaseYear = 1927,
                            Title = "Nutuk"
                        });
                });

            modelBuilder.Entity("BookLibraryEF.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "ali.yilmaz@example.com",
                            Name = "Ali Yilmaz"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "ayse.demir@example.com",
                            Name = "Ayse Demir"
                        });
                });

            modelBuilder.Entity("BookUser", b =>
                {
                    b.Property<int>("BooksBookID")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserID")
                        .HasColumnType("int");

                    b.HasKey("BooksBookID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("BookUser", (string)null);
                });

            modelBuilder.Entity("BookLibraryEF.Models.Book", b =>
                {
                    b.HasOne("BookLibraryEF.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookUser", b =>
                {
                    b.HasOne("BookLibraryEF.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibraryEF.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibraryEF.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
